[project]
name = "noo-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sakib669", email = "stewieboyyy@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "prisma>=0.15.0",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
noo-blog = "noo_blog:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
